"""Add whatsapp_number to users

Revision ID: a322b06e35fc
Revises: 097bbe18f51f
Create Date: 2026-07-23 03:18:13.949159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a322b06e35fc'
down_revision: Union[str, Sequence[str], None] = '097bbe18f51f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('whatsapp_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'whatsapp_number')
    # ### end Alembic commands ###
